"""
BYMA TOOLS - WAF Detector & Bypass
Tools untuk mendeteksi dan bypass Web Application Firewall
"""
import requests
import random
import time
import json
from pathlib import Path
from core.colors import (
    print_success, print_error, print_warning, print_info,
    print_result, print_section, cprint, Colors
)
from core.logger import get_logger
from core.database import get_database


class WAFDetector:
    """WAF Detection and Bypass"""
    
    def __init__(self):
        self.logger = get_logger()
        self.db = get_database()
        self.waf_detected = None
        self.bypass_techniques = []
    
    def detect(self, url, output=None):
        """Detect WAF"""
        print_section(f"WAF Detection: {url}")
        
        # Create scan record
        scan_id = self.db.create_scan("waf_detect", url, "vulnerability")
        self.logger.scan_start("waf_detect", url)
        
        try:
            # Ensure URL has protocol
            if not url.startswith(('http://', 'https://')):
                url = f"http://{url}"
            
            # Run detection tests
            print_info("Running WAF detection tests...")
            waf_info = self._detect_waf(url)
            
            if waf_info:
                self.waf_detected = waf_info
                print_success(f"WAF Detected: {waf_info['name']}")
                
                # Try bypass techniques
                print_info("Testing bypass techniques...")
                self._test_bypasses(url, waf_info)
            else:
                print_success("No WAF detected")
            
            # Display results
            self._display_results()
            
            # Save to database
            if self.waf_detected:
                self.db.add_vulnerability(
                    scan_id, url, 'WAF Detected', 'INFO',
                    f"WAF Detected: {self.waf_detected['name']}",
                    f"WAF detected on target: {self.waf_detected['name']}",
                    f"Vendor: {self.waf_detected.get('vendor', 'Unknown')}",
                    "Consider WAF bypass techniques for testing"
                )
            
            self.db.update_scan(scan_id, "completed", 1)
            self.logger.scan_complete("waf_detect", url, 1)
            
            if output:
                self._save_results(url, output)
            
            return self.waf_detected
        
        except Exception as e:
            self.db.update_scan(scan_id, "failed")
            self.logger.scan_error("waf_detect", url, str(e))
            print_error(f"WAF detection failed: {e}")
            return None
    
    def _detect_waf(self, url):
        """Detect WAF using various techniques"""
        waf_signatures = {
            'Cloudflare': {
                'headers': ['cf-ray', 'cf-cache-status', 'cloudflare'],
                'cookies': ['__cfduid', 'cf_clearance'],
                'body': ['cloudflare', 'cf-browser-verification'],
                'status': [403, 503]
            },
            'Akamai': {
                'headers': ['x-akamai', 'akamai'],
                'cookies': ['akamai'],
                'body': ['akamai', 'reference #[0-9]'],
                'status': [403, 405]
            },
            'AWS WAF': {
                'headers': ['x-amzn-', 'aws'],
                'cookies': ['aws-waf-token'],
                'body': ['aws', 'x-amzn'],
                'status': [403]
            },
            'ModSecurity': {
                'headers': ['mod_security', 'modsecurity'],
                'cookies': [],
                'body': ['mod_security', 'modsecurity', 'this error was generated by mod_security'],
                'status': [403, 406]
            },
            'Imperva': {
                'headers': ['x-iinfo', 'imperva'],
                'cookies': ['visid_incap_', 'incap_ses_'],
                'body': ['imperva', 'incapsula'],
                'status': [403]
            },
            'Sucuri': {
                'headers': ['x-sucuri', 'sucuri'],
                'cookies': ['sucuri'],
                'body': ['sucuri', 'access denied'],
                'status': [403]
            },
            'Barracuda': {
                'headers': ['barra_counter_session'],
                'cookies': ['barra_counter_session'],
                'body': ['barracuda'],
                'status': [403]
            },
            'F5 BIG-IP': {
                'headers': ['bigip', 'x-wa-info'],
                'cookies': ['BIGipServer', 'TS[0-9a-f]+'],
                'body': [],
                'status': [403]
            },
            'FortiWeb': {
                'headers': ['fortiweb'],
                'cookies': [],
                'body': ['fortiweb', 'server unavailable'],
                'status': [403]
            },
            'DenyAll': {
                'headers': ['x-denied'],
                'cookies': [],
                'body': [],
                'status': [403]
            }
        }
        
        # Test 1: Check headers
        print_info("  Checking response headers...")
        try:
            response = requests.get(url, timeout=10, verify=False)
            headers_lower = {k.lower(): v for k, v in response.headers.items()}
            
            for waf_name, signatures in waf_signatures.items():
                for header_sig in signatures['headers']:
                    if any(header_sig in k for k in headers_lower.keys()):
                        return {
                            'name': waf_name,
                            'method': 'header',
                            'signature': header_sig,
                            'evidence': f"Header: {header_sig}"
                        }
        except:
            pass
        
        # Test 2: Check cookies
        print_info("  Checking cookies...")
        try:
            response = requests.get(url, timeout=10, verify=False)
            cookies = [c.lower() for c in response.cookies.keys()]
            
            for waf_name, signatures in waf_signatures.items():
                for cookie_sig in signatures['cookies']:
                    if any(cookie_sig in c for c in cookies):
                        return {
                            'name': waf_name,
                            'method': 'cookie',
                            'signature': cookie_sig,
                            'evidence': f"Cookie: {cookie_sig}"
                        }
        except:
            pass
        
        # Test 3: Check response body
        print_info("  Checking response body...")
        try:
            response = requests.get(url, timeout=10, verify=False)
            body = response.text.lower()
            
            for waf_name, signatures in waf_signatures.items():
                for body_sig in signatures['body']:
                    if body_sig.lower() in body:
                        return {
                            'name': waf_name,
                            'method': 'body',
                            'signature': body_sig,
                            'evidence': f"Body contains: {body_sig}"
                        }
        except:
            pass
        
        # Test 4: Trigger WAF with malicious payload
        print_info("  Testing with malicious payloads...")
        test_payloads = [
            '<script>alert(1)</script>',
            "' OR '1'='1",
            '../../etc/passwd',
            'cat /etc/passwd'
        ]
        
        for payload in test_payloads:
            try:
                test_url = f"{url}?test={payload}"
                response = requests.get(test_url, timeout=10, verify=False)
                
                if response.status_code in [403, 406, 501]:
                    body = response.text.lower()
                    for waf_name, signatures in waf_signatures.items():
                        if response.status_code in signatures['status']:
                            for body_sig in signatures['body']:
                                if body_sig.lower() in body:
                                    return {
                                        'name': waf_name,
                                        'method': 'payload',
                                        'signature': body_sig,
                                        'evidence': f"Triggered by payload: {payload}"
                                    }
            except:
                pass
        
        return None
    
    def _test_bypasses(self, url, waf_info):
        """Test WAF bypass techniques"""
        bypass_techniques = [
            {'name': 'Case Variation', 'payload': '<ScRiPt>alert(1)</ScRiPt>'},
            {'name': 'URL Encoding', 'payload': '%3Cscript%3Ealert(1)%3C/script%3E'},
            {'name': 'Double Encoding', 'payload': '%253Cscript%253Ealert(1)%253C/script%253E'},
            {'name': 'Unicode', 'payload': '\u003cscript\u003ealert(1)\u003c/script\u003e'},
            {'name': 'Null Byte', 'payload': '<sc\u0000ript>alert(1)</sc\u0000ript>'},
            {'name': 'Comment Obfuscation', 'payload': '<scr<!-- -->ipt>alert(1)</scr<!-- -->ipt>'},
            {'name': 'Chunked Transfer', 'payload': 'chunked'},
            {'name': 'HTTP Parameter Pollution', 'payload': 'test=1&test=2'},
        ]
        
        for technique in bypass_techniques:
            try:
                test_url = f"{url}?test={technique['payload']}"
                response = requests.get(test_url, timeout=10, verify=False)
                
                if response.status_code == 200:
                    self.bypass_techniques.append({
                        'name': technique['name'],
                        'payload': technique['payload'],
                        'status': response.status_code,
                        'success': True
                    })
                    print_success(f"  Bypass possible: {technique['name']}")
                else:
                    self.bypass_techniques.append({
                        'name': technique['name'],
                        'payload': technique['payload'],
                        'status': response.status_code,
                        'success': False
                    })
            except:
                pass
    
    def _display_results(self):
        """Display WAF detection results"""
        print_section("WAF Detection Results")
        
        if self.waf_detected:
            cprint(f"    WAF Detected: {self.waf_detected['name']}", Colors.BRED)
            cprint(f"    Detection Method: {self.waf_detected['method']}", Colors.BWHITE)
            cprint(f"    Evidence: {self.waf_detected['evidence']}", Colors.BWHITE)
        else:
            cprint(f"    No WAF Detected", Colors.BGREEN)
        
        # Display bypass techniques
        if self.bypass_techniques:
            print()
            cprint(f"    Bypass Techniques Tested: {len(self.bypass_techniques)}", Colors.BCYAN)
            
            successful = [t for t in self.bypass_techniques if t['success']]
            failed = [t for t in self.bypass_techniques if not t['success']]
            
            cprint(f"      Successful: {len(successful)}", Colors.BGREEN)
            cprint(f"      Blocked: {len(failed)}", Colors.BRED)
            
            if successful:
                print()
                cprint(f"    Potential Bypasses:", Colors.BGREEN)
                for technique in successful:
                    cprint(f"      - {technique['name']}", Colors.BWHITE)
    
    def _save_results(self, url, output_file):
        """Save results to file"""
        try:
            output_path = Path(output_file)
            output_path.parent.mkdir(parents=True, exist_ok=True)
            
            with open(output_path, 'w') as f:
                json.dump({
                    'url': url,
                    'waf_detected': self.waf_detected,
                    'bypass_techniques': self.bypass_techniques
                }, f, indent=2)
            
            print_success(f"Results saved to {output_file}")
        except Exception as e:
            print_error(f"Failed to save results: {e}")


class WAFFingerprint:
    """Advanced WAF fingerprinting"""
    
    def __init__(self):
        self.logger = get_logger()
    
    def fingerprint(self, url):
        """Perform detailed WAF fingerprinting"""
        print_section("Advanced WAF Fingerprinting")
        
        fingerprints = {}
        
        # Test 1: Response time analysis
        print_info("Analyzing response times...")
        fingerprints['response_time'] = self._analyze_response_time(url)
        
        # Test 2: Error page analysis
        print_info("Analyzing error pages...")
        fingerprints['error_page'] = self._analyze_error_page(url)
        
        # Test 3: Header analysis
        print_info("Analyzing headers...")
        fingerprints['headers'] = self._analyze_headers(url)
        
        # Test 4: Cookie analysis
        print_info("Analyzing cookies...")
        fingerprints['cookies'] = self._analyze_cookies(url)
        
        return fingerprints
    
    def _analyze_response_time(self, url):
        """Analyze response time patterns"""
        times = []
        
        for _ in range(5):
            try:
                start = time.time()
                requests.get(url, timeout=10, verify=False)
                elapsed = time.time() - start
                times.append(elapsed)
            except:
                pass
        
        if times:
            avg_time = sum(times) / len(times)
            return {
                'avg_response_time': avg_time,
                'min_response_time': min(times),
                'max_response_time': max(times)
            }
        
        return None
    
    def _analyze_error_page(self, url):
        """Analyze WAF error page"""
        try:
            # Trigger error
            test_url = f"{url}?{random.randint(1000, 9999)}"
            response = requests.get(test_url, timeout=10, verify=False)
            
            return {
                'status_code': response.status_code,
                'content_length': len(response.text),
                'contains_waf_fingerprint': self._check_waf_fingerprint(response.text)
            }
        except:
            return None
    
    def _analyze_headers(self, url):
        """Analyze response headers"""
        try:
            response = requests.get(url, timeout=10, verify=False)
            return dict(response.headers)
        except:
            return {}
    
    def _analyze_cookies(self, url):
        """Analyze cookies"""
        try:
            response = requests.get(url, timeout=10, verify=False)
            return {c.name: c.value for c in response.cookies}
        except:
            return {}
    
    def _check_waf_fingerprint(self, body):
        """Check for WAF fingerprint in response body"""
        fingerprints = [
            'cloudflare', 'akamai', 'aws', 'imperva', 'sucuri',
            'mod_security', 'barracuda', 'fortiweb', 'denyall'
        ]
        
        body_lower = body.lower()
        for fp in fingerprints:
            if fp in body_lower:
                return True
        
        return False
